---
cog_bundle_version: 3
name: fleet
description: Interact with CoreOS Fleet
version: '0.1'
docker:
  image: geowa4/cog-fleet
  tag: 'latest'
  binds:
    - /var/run/fleet.sock:/var/run/fleet.sock
commands:
  unit:
    executable: /usr/bin/cog-command
    description: Interact with Fleet units
    documentation: |
      Interact with Fleet units.

      fleet:unit list [--filter <text>]
    options:
      filter:
        type: string
        required: false
    rules: [ 'allow' ]
